- name: Install apache web server with php support
  hosts: wordpress
  gather_facts: false
  tasks:
    - name: Install web server sequence
      become: true
      block:
        - name: Ensure required app exists
          pkgng:
            name:
              - apache24
              - php81
              - mod_php81
              - wordpress
            state: present
        
        - name: Enable rc.conf to enable apache24
          lineinfile:
            path: /etc/rc.conf
            line: "{{ item }}"
            create: true
          loop:
            - apache24_enable="YES"
            - apache24_http_accept_enable="YES"

        - name: Set ownership to www for wordpress folder
          file:
            path: /usr/local/www/wordpress
            state: directory
            recurse: true
            owner: www
            group: www

        - name: Copy httpd.conf to adjust php service (local to remote)
          copy:
            src: files/httpd.conf
            dest: /usr/local/etc/apache24/httpd.conf
          notify: Restart apache24
        
        - name: Check if wp-config.php already exists
          register: wp_config_path
          stat:
            path: /usr/local/www/wordpress/wp-config.php

        - name: Template wp-config.php
          when: not wp_config_path.stat.exists | d(false)
          template:
            src: templates/wp-config.php.j2
            dest: /usr/local/www/wordpress/wp-config.php
        
        - name: Restart apache24
          service:
            name: apache24
            state: restarted

    - name: Install local db sequence
      become: true
      block:
        - name: Ensure required DB app exists
          pkgng:
            name:
              - mariadb106-server
            state: present

        - name: Edit rc.conf to enable mysql
          register: mysql_rc_conf
          lineinfile:
            path: /etc/rc.conf
            line: mysql_enable="YES"
            create: yes

        - name: Restart DB Service
          when: mysql_rc_conf.changed | d(false)
          service:
            name: mysql-server
            state: restarted

        - name: Set mysql root password
          changed_when: false
          command: mysqladmin -u root password '{{ mysql_root_password }}'

        - name: Check existing database
          changed_when: false
          register: mysql_db_exists
          shell: mysql -e "show databases" | grep {{ mysql_wordpress_database }}; exit 0
        
        # Sementara bikin DB Manual
        - name: Create database and user for wordpress
          register: mysql_db
          when: mysql_db_exists.stdout_lines | length == 0
          changed_when: "'database exists' not in mysql_db.stderr"
          shell: >-
            mysql -e "
            create database {{ mysql_wordpress_database }};
            grant all on {{ mysql_wordpress_database }}.* to {{ mysql_wordpress_user }}@127.0.0.1 identified by '{{ mysql_wordpress_pass }}';
            grant all on {{ mysql_wordpress_database }}.* to {{ mysql_wordpress_user }}@localhost identified by '{{ mysql_wordpress_pass }}';
            "; exit 0